version: short
module: default
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: /css
  static_dir: css
- url: /.*
  script: main.app
  login: optional
